on: 
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/run_publish_package.yaml"
    branches:
      - "package-*"

name: Publish Package

env:
  GalleryName: PrivateScubaGearGallery

jobs:
  Run-Smoke-Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Register private PowerShell package repository
        shell: powershell
        run: |
          $PSGalleryPath = 'D:\PrivateGallery'
          New-Item -Path $PSGalleryPath -ItemType Directory
          $Splat = @{ Name = $GalleryName, SourceLocation = $PSGalleryPath, PublishLocation = $PSGalleryPath, InstallationPolicy = 'Trusted' }
          Register-PSRepository @Splat 
      - name: Publish ScubaGear Module 
        shell: powershell
        run: |
          Publish-Module -Path repo\ScubaGear\PowerShell\ScubaGear\ -Repository $GalleryName
      - name: Test Module Publish
        shell: powershell
        run: |
          Find-Module -Name ScubaGear -Repository $GalleryName
          Install-Module -Name ScubaGear
          
